---
- name: Create a new ACME account with Let's Encrypt Staging
  hosts: localhost
  gather_facts: false

#
#  new script, cred, vault needs to have 
#           acme_directory: "{{ acme_directory }}"
#           account_email: "{{ contact }}"
#           account_key_content: "{{ key }}"
#



  tasks:
    - name: 01 - Generate a EC384 bit ECC Private Key
      community.crypto.openssl_privatekey:
        curve: secp384r1
        type: ECC
        path: ~/le_private_key.pem


    - name: 02 - Extract the Public Key
      community.crypto.openssl_publickey:
        path: ~/le_public_key.pem
        privatekey_path: ~/le_private_key.pem


    - name: 03 - Create a new secret and store the two keys
      community.hashi_vault.vault_kv2_write:
        path: "{{ key_name }}"
        url: "{{ vault_url }}"
        auth_method: "{{ vault_auth_method }}"
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_mount }}"
        data:
          public_key: "{{ lookup('file', '~/le_public_key.pem') }}"
          private_key: "{{ lookup('file', '~/le_private_key.pem') }}"


    - name: 05 - Create ACME account on the server
      community.crypto.acme_account:
        account_key_src: ~/le_private_key.pem
        acme_directory: "{{ acme_directory }}"
        acme_version: 2
        contact:
          - "{{ acme_email_address }}"
        state: present
        terms_agreed: true
      register: acme_account


    - name: 06 - Display ACME account details
      ansible.builtin.debug:
        var: acme_account


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play

