---
- name: Create a new ACME account with Let's Encrypt Staging
  hosts: localhost
  gather_facts: false
  vars:
   vault_url: "https://vault.theglens.net:8200"
   vault_mount: "kv"

  tasks:

   - name: 01 - Use OpenSSL to Generate a Private Key
     community.crypto.openssl_privatekey:
       curve: secp384r1
       type: ECC
       path: ~/le_private_key.pem


   - name: 02 - Use OpenSSL to Extract the Public Key
     community.crypto.openssl_publickey:
       path: ~/le_public_key.pem
       privatekey_path: ~/le_private_key.pem


   - name: 03 - Create a new secret and store the two keys
     community.hashi_vault.vault_kv2_write:
       url: "https://vault.theglens.net:8200"
       path: "{{ key_name }}"
       auth_method: token
       token: "{{ ansible_password }}"
       engine_mount_point: "kv"
       data:
         public_key: "{{ lookup('file', '~/le_public_key.pem') }}"
         private_key: "{{ lookup('file', '~/le_private_key.pem') }}"


   - name: 05 - Create ACME account on the server
     community.crypto.acme_account:
       account_key_src: ~/le_private_key.pem
       acme_directory: "{{ acme_directory }}"
       acme_version: 2
       contact:
         - "{{ acme_email_address }}"
       state: present
       terms_agreed: true
     register: acme_account


   - name: 06 - Display ACME account details
     ansible.builtin.debug:
       var: acme_account

   - name: Timmay HARD STOP this Playbook
     ansible.builtin.meta: end_play
